### ISSUE TITLE
Tp ended

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-1-greyl_varrel#1]
* ⚠️ pourquoi créer des variables locales dans `addEdge`?

* 👍 Bonne implementation des patterns

**Comment by Lilian-Tacos** [comment]
Pour les variables locales, on n'a pas encore l'habitude d'appeler les constructeurs dans une fonction, la plupart du temps on les appelle pour initialiser une variable.
C'est remplacer, merci 👍

**Comment by magnYbor** [comment]
Petite question concernant l'implémentation de l'iterator : en regardant les issues d'autres groupes il y a souvent le problème de pré-remplissage de la liste / pile qui revient, au lieu de la remplir au fur et à mesure que next() est appelé. C'est à peu près ce que notre programme fait, c'est valide ou pas ?

**Comment by Slashgear** [comment]
Désolé, je n'avais pas vu. Jusqu'ici, rien ne prouve que je sois un terminator 🤖 
C'est à corrigé

Tu appelles dans ton constructeur le createList() qui t'initialise tout ton parcours.
Et je veux pas ça, c'est pas la bonne implem du pattern.

Je veux qu'à chaque appel, tu update ta liste avec ton parcours.
En gros ce sont tes fonctions d'ajout dans la liste à traiter et de suppression de la liste à traiter qui doivent être génériques. (ajout en tete / en queue, retirer en tete ou en queue en fonction du parcours)

**Comment by magnYbor** [comment]
@Slashgear C'est corrigé 👍

**Comment by Slashgear** [comment]
👍
